{
  "formatVersion": "1.1",
  "component": {
    "group": "com.codelang.jitpack",
    "module": "hook",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "hook-1.0.aar",
          "url": "hook-1.0.aar",
          "size": 41689,
          "sha512": "7b41cc7e037a2cb99303dc26ca21d76cceca83247c94244dba8efdbb236f0c72fdb161661f11a7e6cb34ccc29f17ccd87b6ab4f372fda2358394950fc99fc0e8",
          "sha256": "5b86a459157b50d1a6dc35238874cc63df9d51b033d3b6fdca893c1ffe4f1789",
          "sha1": "14828a556963eb88dd1249dea1eec2bd78f924f7",
          "md5": "e2a2308152f201e54c24dee3c4ad5926"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "hook-1.0.aar",
          "url": "hook-1.0.aar",
          "size": 41689,
          "sha512": "7b41cc7e037a2cb99303dc26ca21d76cceca83247c94244dba8efdbb236f0c72fdb161661f11a7e6cb34ccc29f17ccd87b6ab4f372fda2358394950fc99fc0e8",
          "sha256": "5b86a459157b50d1a6dc35238874cc63df9d51b033d3b6fdca893c1ffe4f1789",
          "sha1": "14828a556963eb88dd1249dea1eec2bd78f924f7",
          "md5": "e2a2308152f201e54c24dee3c4ad5926"
        }
      ]
    }
  ]
}
