# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 下面是多个step ，每个以“-”开头
      # step：检查分支
      - uses: actions/checkout@v1
      # step：设置jdk版本
      # step 名称
      - name: set up JDK 11
        # 引用公共action
        uses: actions/setup-java@v1
        with:
          # 设置参数
          java-version: 11
      # step：打包apk
      - name: Build with Gradle
        # 运行命令
        run: chmod +x gradlew &&./gradlew publish
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:MRwangqi/Maven.git
          SQUASH_HISTORY: "false"
          CLEAR_GLOBS_FILE: ".clear-target-files"
          BRANCH:  main
          FOLDER: build/repo
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
     
